import Link from 'next/link'
import { ShieldCheck, X } from 'lucide-react'
import { AppShell } from '@/components/app-shell'

export const metadata = {
  title: 'Adatvédelmi Nyilatkozat',
  description: 'A Mesterek adatkezelési tájékoztatója és az érintettek GDPR szerinti jogai.',
}

const sections = [
  { title: '1. Adatkezelő', text: ['Barna János Mester (Enskild firma), Kvarngatan 6, 533 30 Götene, Svédország. Cégjegyzékszám (Org.nr): 19930124-2930; EU VAT: SE930124293001. Kapcsolat: info@mesterek.eu.'] },
  { title: '2. Kezelt adatok és célok', text: ['Szakember-regisztrációkor kapcsolattartási, szakmai, számlázási, adózási, előfizetési és biztonsági adatokat kezelünk a profil létrehozásához, ellenőrzéséhez, közzétételéhez, a szerződés teljesítéséhez, számlázáshoz, visszaélés-megelőzéshez és ügyfélszolgálathoz.', 'Látogatóktól a webhely biztonságos működéséhez szükséges technikai adatokat és cookie-választást kezeljük. Opcionális analitika kizárólag előzetes hozzájárulás után működik.'] },
  { title: '3. Jogalapok', text: ['Az adatkezelés jogalapja a szerződés megkötése és teljesítése, jogi kötelezettség, a platform biztonságos működéséhez fűződő jogos érdek, valamint az opcionális cookie-k esetén az önkéntes hozzájárulás. A hozzájárulás bármikor visszavonható, ez nem érinti a korábbi adatkezelés jogszerűségét.'] },
  { title: '4. Adatfeldolgozók és továbbítás', text: ['A Vercel tárhely- és infrastruktúra-szolgáltatást, a Neon adatbázis-infrastruktúrát, a Stripe fizetési és előfizetési szolgáltatást, a Bokio könyvelési támogatást biztosít. A Mesterek.eu teljes bankkártyaadatot nem kap meg és nem tárol.', 'Az Európai Gazdasági Térségen kívüli adattovábbítás csak megfelelő garanciák – például megfelelőségi határozat vagy uniós általános szerződési feltételek – mellett történhet.'] },
  { title: '5. Online fizetés és adatfeldolgozás', text: ['A biztonságos online bankkártyás fizetések és az előfizetések feldolgozója a Stripe, Inc. A fizetési művelet során szükséges kártya- és tranzakciós adatokat a Stripe saját biztonságos rendszerében, önálló adatkezelési feltételei szerint kezeli.', 'A Mesterek.eu a nyers bankkártyaszámokat nem tárolja, azokhoz nem fér hozzá, és azokat saját szerverein nem kezeli. A Stripe adatkezeléséről a Stripe adatvédelmi tájékoztatójában olvashat.'] },
  { title: '6. Megőrzési idők', text: ['A profil- és fiókadatokat a fiók fennállásáig, illetve törlésig kezeljük. A kötelező minimális számviteli bizonylatadatokat a svéd számviteli előírásoknak megfelelően 8 évig őrizzük. A cookie-hozzájárulás legfeljebb egy évig marad meg. Biztonsági és jogi adatokat csak a szükséges, arányos ideig tartunk meg.'] },
  { title: '7. Az érintettek jogai', text: ['Kérhető hozzáférés, helyesbítés, törlés, korlátozás, adathordozhatóság, valamint tiltakozás a jogos érdeken alapuló adatkezelés ellen. A szakemberfiók közvetlenül törölhető az irányítópult Biztonság részében; a nem kötelező személyes és működési adatok törlődnek vagy anonimizálódnak.', 'Kérelem az info@mesterek.eu címen nyújtható be. A személyazonosság védelme érdekében az adatkezelő további azonosítást kérhet. Panasz benyújtható a svéd Integritetsskyddsmyndigheten (IMY) felügyeleti hatósághoz, illetve az érintett szokásos tartózkodási helye szerinti felügyeleti hatósághoz.'] },
  { title: '8. Biztonság és változások', text: ['Technikai és szervezési intézkedéseket alkalmazunk, többek között titkosított kapcsolatot, hozzáférés-szabályozást, naplózást és szolgáltatói biztonsági kontrollokat. Lényeges változás esetén a tájékoztatót frissítjük, és szükség esetén külön értesítést adunk.'] },
] as const

export default function PrivacyPage() {
  return <AppShell><div className="page-wrap"><article className="relative mx-auto w-full max-w-4xl rounded-2xl border-2 border-border bg-card p-6 pt-20 shadow-sm md:p-10 md:pt-20">
    <Link href="/" className="absolute right-4 top-4 flex size-12 items-center justify-center rounded-xl border-2 border-border bg-background text-foreground transition hover:border-primary hover:text-primary focus-visible:outline-4" aria-label="Adatvédelmi Nyilatkozat bezárása és vissza a kezdőlapra"><X className="size-6" aria-hidden="true" /></Link>
    <div className="flex items-start gap-4"><div className="flex size-14 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground"><ShieldCheck className="size-8" aria-hidden="true" /></div><div><p className="font-mono text-sm font-bold uppercase tracking-wider text-muted-foreground">Hatályos: 2026. augusztus 19.</p><h1 className="mt-2 text-balance text-3xl font-black tracking-tight text-primary md:text-5xl">Adatvédelmi Nyilatkozat</h1></div></div>
    <p className="mt-6 text-pretty text-lg leading-relaxed text-muted-foreground">Tájékoztató a Mesterek.eu adatkezeléséről és az Önt megillető jogokról.</p>
    <div className="mt-10 flex flex-col gap-9">{sections.map((section) => <section key={section.title}><h2 className="text-balance text-2xl font-black text-primary">{section.title}</h2><div className="mt-3 flex flex-col gap-3 text-base leading-relaxed md:text-lg">{section.text.map((paragraph) => <p key={paragraph}>{paragraph.split(/(info@mesterek\.eu|Stripe adatvédelmi tájékoztatójában)/).map((part, index) => part === 'info@mesterek.eu' ? <a key={`${section.title}-${index}`} href="mailto:info@mesterek.eu" className="font-bold underline underline-offset-4">info@mesterek.eu</a> : part === 'Stripe adatvédelmi tájékoztatójában' ? <a key={`${section.title}-${index}`} href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" className="font-bold text-primary underline underline-offset-4">Stripe adatvédelmi tájékoztatójában<span className="sr-only"> (új lapon nyílik meg)</span></a> : <span key={`${section.title}-${index}`}>{part}</span>)}</p>)}</div></section>)}</div>
  </article></div></AppShell>
}
