import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { AppShell } from '@/components/app-shell'
import { ProfessionalCard } from '@/components/professional-card'
import { CATEGORIES } from '@/lib/constants'
import { locationBySlug, slugifyHungarian } from '@/lib/hungary-locations'
import { searchProfessionals } from '@/lib/professionals'

type Props = { params: Promise<{ categorySlug: string; citySlug: string }> }
function resolveCategory(slug: string) { return CATEGORIES.find((item) => item.key === slug || slugifyHungarian(item.name) === slug) }
function inflectedCategory(name: string) { return name.endsWith('ő') ? `${name.slice(0, -1)}ők` : `${name}k` }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { categorySlug, citySlug } = await params; const category = resolveCategory(categorySlug); const location = locationBySlug(citySlug); if (!category || !location) return {}; const result = await searchProfessionals({ category: category.name, city: location.city }); if (!result.total) return { robots: { index: false, follow: false } }; const title = `A legjobb ${inflectedCategory(category.name)} ${location.city} városában | Mesterek.eu`; const description = `Ellenőrzött ${category.name.toLocaleLowerCase('hu-HU')} szakemberek ${location.city} területén. Telefonszámok, bemutatkozások és kiemelt mesterek egy helyen.`; const canonical = `/${category.key}/${slugifyHungarian(location.city)}`; return { title, description, alternates: { canonical }, openGraph: { title, description, url: canonical, type: 'website' } } }
export default async function SeoDirectoryPage({ params }: Props) { const { categorySlug, citySlug } = await params; const category = resolveCategory(categorySlug); const location = locationBySlug(citySlug); if (!category || !location) notFound(); const result = await searchProfessionals({ category: category.name, city: location.city }); if (!result.total) notFound(); return <AppShell><main className="page-wrap"><nav className="text-sm font-bold text-muted-foreground" aria-label="Morzsamenü"><Link href="/">Főoldal</Link> / <Link href={`/kereses?kategoria=${encodeURIComponent(category.name)}`}>{category.name}</Link> / {location.city}</nav><header className="mt-6 max-w-4xl"><p className="font-black text-primary">{location.county} megye · {result.total} jóváhagyott szakember</p><h1 className="page-title mt-2">A legjobb {inflectedCategory(category.name)} {location.city} városában</h1><p className="page-lead">Hasonlítsa össze a helyi szakembereket, nézze meg bemutatkozásukat, és lépjen kapcsolatba velük közvetlenül. A Kiemelt Mesterek elsőként jelennek meg.</p></header><section className="mt-8 flex flex-col gap-4" aria-label={`${category.name} szakemberek ${location.city} városában`}>{result.items.map((professional) => <ProfessionalCard key={professional.id} professional={professional} />)}</section><section className="surface mt-10"><h2 className="text-2xl font-black">{category.name} keresése {location.city} területén</h2><p className="mt-3 leading-relaxed text-muted-foreground">A Mesterek.eu kizárólag jóváhagyott adatlapokat jelenít meg ezen az oldalon. Telefonos érdeklődése közvetlenül a választott szakemberhez fut be.</p></section></main></AppShell> }
